# Generated by Django 4.2 on 2023-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_order', models.IntegerField(default=1, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.CharField(default='No description provided yet!', max_length=100)),
                ('times_performed', models.IntegerField(default=0)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='action_cover_images/')),
                ('cover_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='action_video/')),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
