# Generated by Django 4.2 on 2023-04-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
    ]
