# Generated by Django 4.2 on 2023-04-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.CharField(max_length=100)),
                ('step2', models.CharField(max_length=100)),
                ('step3', models.CharField(max_length=100)),
                ('step4', models.CharField(max_length=100)),
                ('step5', models.CharField(max_length=100)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.actions')),
            ],
            options={
                'verbose_name': 'Action Step',
                'verbose_name_plural': 'Action Steps',
            },
        ),
    ]
