# Generated by Django 4.2 on 2023-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_actionsteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='media/action_cover_images/'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/action_video/'),
        ),
    ]
