# Generated by Django 4.2 on 2023-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_actions_cover_image_alter_actions_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='description',
            field=models.TextField(default='No description provided yet!'),
        ),
        migrations.AlterField(
            model_name='actionsteps',
            name='step1',
            field=models.TextField(default='Step 1'),
        ),
        migrations.AlterField(
            model_name='actionsteps',
            name='step2',
            field=models.TextField(default='Step 2'),
        ),
        migrations.AlterField(
            model_name='actionsteps',
            name='step3',
            field=models.TextField(default='Step 3'),
        ),
        migrations.AlterField(
            model_name='actionsteps',
            name='step4',
            field=models.TextField(default='Step 4'),
        ),
        migrations.AlterField(
            model_name='actionsteps',
            name='step5',
            field=models.TextField(default='Step 5'),
        ),
    ]
