# Generated by Django 4.2 on 2023-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_performlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='actions',
            name='cover_image_url',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
