# Generated by Django 4.2 on 2023-04-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_actions_cover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='cover_image_url',
        ),
    ]
