# Generated by Django 4.2 on 2023-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_actions_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/action_cover/'),
        ),
    ]
