# Generated by Django 4.2 on 2023-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_actions_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='action_cover_images/'),
        ),
        migrations.AlterField(
            model_name='performlogs',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='action_input_file/'),
        ),
        migrations.AlterField(
            model_name='performlogs',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='action_output_file/'),
        ),
    ]
