# Generated by Django 4.2 on 2023-04-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_actions_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='action_media/')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.actions')),
            ],
            options={
                'verbose_name': 'Action Media',
                'verbose_name_plural': 'Action Media',
            },
        ),
    ]
