# Generated by Django 4.2 on 2023-04-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_actionmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionmedia',
            options={},
        ),
    ]
