# Generated by Django 4.2 on 2023-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_actionmedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_order',
            field=models.IntegerField(default=0),
        ),
    ]
