# Generated by Django 4.2 on 2023-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_actions_action_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionmedia',
            name='media',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='actionmedia',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
