# Generated by Django 4.2 on 2023-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_actionmedia_media_remove_actions_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='action_media/'),
        ),
        migrations.AddField(
            model_name='actions',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='action_cover_images/'),
        ),
    ]
